# Generated by Django 4.2.23 on 2025-09-15 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='manager_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managertask_employeetask', to='task.managertask'),
        ),
        migrations.AlterField(
            model_name='managertask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_managertask', to='task.project'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='employee_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employeetask_massage', to='task.employeetask'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
