# Generated by Django 4.2.23 on 2025-09-24 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_attendance_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
                    model_name='ManagerTask', # Replace with your model's name
                    old_name='start_date', # The original field name
                    new_name='manager_start_date', # The new desired field name
                ),
    ]
