# Generated by Django 4.2.23 on 2025-09-24 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20250924_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managertask',
            old_name='end_date',
            new_name='manager_end_date',
        ),
    ]
