# Generated by Django 4.2.23 on 2025-09-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_manager_start_date_managertask_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='EmployeeTask',
            old_name='task_start_date',
            new_name='employee_start_date',
        ),
        migrations.RenameField(
            model_name='EmployeeTask',
            old_name='task_end_date',
            new_name='employee_end_date',
        ),
    ]
